// Quotes.ts

export const quotes: string[] = [
  // Original SASP-specific quotes
  "Professionalism is more than a uniform—it’s the trust we build in every call, every action, every moment.",
  "Structure is what transforms chaos into control—build it, respect it, live it.",
  "Discipline isn’t given—it’s earned every day, in every decision you make.",
  "Join the elite: be the trooper who others look up to, even on their worst days.",
  "SASP is where structure and discipline meet courage and integrity—join state police and find your purpose.",
  "Professionalism is the badge that sets us apart—wear it with pride.",
  "Structure: the difference between a good response and a great one.",
  "Discipline: the force that keeps us steady when others would falter.",
  "Join the elite—be the trooper who others want by their side when everything goes wrong.",
  "Join state police and discover the strength that comes from wearing the same badge as heroes before you.",
  "Professionalism means every citizen knows: SASP is here, and SASP is ready.",
  "Structure isn’t just paperwork—it’s the reason we’re always prepared for the worst.",
  "Discipline turns potential into performance—master it.",
  "Join the elite, because excellence isn’t a label—it’s a habit.",
  "Join state police and set the bar higher than you ever thought possible.",
  "Professionalism, structure, discipline—these aren’t just words; they’re the pillars of every SASP badge.",
  "Ainsworth always says, ‘Nothing ends a shift like a good cigar.’ He’s living proof that even the toughest troopers need to relax.",
  "Join the elite—because being ordinary has never been our mission.",
  "Fun Fact: Capybaras are the largest rodents on earth—and they know a thing or two about sticking together. Something we could all learn from.",
  "Professionalism, structure, and discipline: the SASP trifecta that turns good troopers into great ones.",

  // Additional quotes on professionalism and integrity
  "People with integrity do what they say they are going to do. Others have excuses. – Dr. Laura Schlessinger",
  "Stand up for what's right, in small matters and large ones, and always do what you promise. – Reuben Mark",
  "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not. – Oprah Winfrey",
  "The foundation stones for a balanced success are honesty, character, integrity, faith, love, and loyalty. – Zig Ziglar",
  "Integrity is choosing courage over comfort; choosing what is right over what is fun, fast, or easy. – Unknown",
  "Trust is earned when honesty meets integrity in every interaction. – Unknown",
  "Integrity is the seed for achievement. It is the principle that never fails. – Earl Nightingale",
  "Your reputation is more important than your paycheck, and your integrity is worth more than your career. – Ryan Freitas",
  "Integrity is the quiet strength to remain honest, even when no one notices. – Unknown",
  "Leadership without integrity is a ship without a compass. – Unknown",
  "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
  "The price of greatness is responsibility. – Winston Churchill",
  "Leadership is not about being in charge. It's about taking care of those in your charge. – Simon Sinek",
  "A leader is one who knows the way, goes the way, and shows the way. – John C. Maxwell",
  "The strength of a nation derives from the integrity of the home. – Confucius",
  "Trust is the glue of life. It's the most essential ingredient in effective communication. – Stephen R. Covey",
  "Earn trust, earn trust, earn trust. Then you can worry about the rest. – Seth Godin",
  "The first law of leadership is that your foundation is built through integrity, character, and trust. – Brian Cagneey",
  "Integrity gives leaders the courage to make hard decisions with a clear conscience. – Unknown",
  "A leader's integrity is the foundation of their influence and strength. – Unknown",

  // Humorous yet professional quotes
  "Luck is a dividend of sweat. The more you sweat, the luckier you get. – Ray Kroc",
  "People often say that motivation doesn't last. Well, neither does bathing—that's why we recommend it daily. – Zig Ziglar",
  "If hard work is the key to success, most people would rather pick the lock. – Claude MacDonald",
  "The only thing that ever sat its way to success was a hen. – Sarah Brown",
  "If you think you are too small to make a difference, try sleeping with a mosquito. – Dalai Lama",
  "You can't have a million-dollar dream with a minimum wage work ethic. – Zig Ziglar",
  "The question isn't who is going to let me, it's who is going to stop me. – Ayn Rand",
  "Even a stopped clock is right twice every day. After some years, it can boast of a long series of successes. – Marie von Ebner-Eschenbach",
  "Nothing is impossible, the word itself says 'I'm possible!' – Audrey Hepburn",
  "If opportunity doesn't knock, build a door. – Milton Berle",
  "Do not take life too seriously. You will never get out of it alive. – Elbert Hubbard",
  "A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them. – John C. Maxwell",
  "Success has many fathers; failures have none. – Philip Caldwell",
  "Don't be afraid to stand for what you believe in, even if you stand alone. – Peter Lawford",
  "When you have made as many mistakes as I have, then you can be as good as me. – Wolfgang Puck",
  "A strong person says what he or she means. A weak person lies to please others. – David Viscott",
  "Becoming a leader is synonymous with becoming yourself. It is precisely that simple and it is also that difficult. – Warren Bennis",
  "Integrity is doing the right thing, even when no one is watching. – C.S. Lewis",
  "The time is always right to do what is right. – Martin Luther King Jr.",
  "Character is much easier kept than recovered. – Thomas Paine",

  // Additional quotes to reach 100
  "Honesty is the first chapter in the book of wisdom. – Thomas Jefferson",
  "The supreme quality for leadership is unquestionably integrity. – Dwight D. Eisenhower",
  "Integrity is telling myself the truth. And honesty is telling the truth to other people. – Spencer Johnson",
  "The measure of a man's real character is what he would do if he knew he would never be found out. – Thomas Babington Macaulay",
  "Live so that when your children think of fairness, caring, and integrity, they think of you. – H. Jackson Brown Jr.",
  "Integrity is the essence of everything successful. – R. Buckminster Fuller",
  "The elevator to success is out of order. You'll have to use the stairs, one step at a time. – Joe Girard",
  "I always wanted to be somebody, but now I realize I should have been more specific. – Lily Tomlin",
  "People say nothing is impossible, but I do nothing every day. – A.A. Milne",
  "Life is like a sewer… what you get out of it depends on what you put into it. – Tom Lehrer",
  "You can't have everything. Where would you put it? – Steven Wright",
  "Work until your bank account looks like a phone number. – Unknown",
  "Change is not a four-letter word… but often your reaction to it is! – Jeffrey Gitomer",
  "Bad decisions make good stories. – Ellis Vidler",
  "When life gives you lemons, squirt someone in the eye. – Cathy Guisewite",
  "A clear conscience is a sure sign of a bad memory. – Mark Twain",
  "Well-behaved women seldom make history. – Laurel Thatcher Ulrich",
  "I didn't fail the test. I just found 100 ways to do it wrong. – Benjamin Franklin",
  "Don't worry about the world coming to an end today. It's already tomorrow in Australia. – Charles Schulz",
  "Be happy – it drives people crazy. – Unknown"
];

export function getRandomQuote(): string {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}
